
API_KEY = 'YOUR_BINANCE_API_KEY'
API_SECRET = 'YOUR_BINANCE_API_SECRET'
OPENAI_KEY = 'YOUR_OPENAI_API_KEY'  # Or Groq API Key
TELEGRAM_TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN'
TELEGRAM_CHAT_ID = 'YOUR_TELEGRAM_CHAT_ID'
SYMBOL = 'XRPUSDT'
QUANTITY = 10
TEST_MODE = True
